SHELL = /bin/sh
SCIDIR=../../..
SCIDIR1=..\..\..

LIBRARY=test.a 

OBJSC = $(patsubst %.c,%.o,$(wildcard *.c))
OBJSF = 

include ../../../Makefile.incl

CFLAGS = $(CC_OPTIONS)
FFLAGS = $(FC_OPTIONS)

include ../../Make.lib

