(defun test ()
  (goto-char (point-min))
  (setq prefix "nsp_[a-z]*_" )
  (replace-regexp (concat prefix "dasum") "C2F(dasum)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "daxpy") "C2F(daxpy)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "dbdsqr") "C2F(dbdsqr)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "dcabs1") "C2F(dcabs1)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "dcopy") "C2F(dcopy)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "ddot") "C2F(ddot)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "dgbcon") "C2F(dgbcon)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "dgbmv") "C2F(dgbmv)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "dgbsv") "C2F(dgbsv)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "dgbtrf") "C2F(dgbtrf)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "dgbtrs") "C2F(dgbtrs)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "dgebak") "C2F(dgebak)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "dgebal") "C2F(dgebal)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "dgebd2") "C2F(dgebd2)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "dgebrd") "C2F(dgebrd)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "dgecon") "C2F(dgecon)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "dgeequ") "C2F(dgeequ)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "dgees") "C2F(dgees)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "dgeesx") "C2F(dgeesx)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "dgeev") "C2F(dgeev)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "dgegs") "C2F(dgegs)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "dgehd2") "C2F(dgehd2)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "dgehrd") "C2F(dgehrd)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "dgelq2") "C2F(dgelq2)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "dgelqf") "C2F(dgelqf)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "dgels") "C2F(dgels)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "dgelsd") "C2F(dgelsd)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "dgelss") "C2F(dgelss)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "dgelsx") "C2F(dgelsx)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "dgelsy") "C2F(dgelsy)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "dgemm") "C2F(dgemm)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "dgemv") "C2F(dgemv)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "dgeql2") "C2F(dgeql2)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "dgeqlf") "C2F(dgeqlf)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "dgeqp3") "C2F(dgeqp3)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "dgeqpf") "C2F(dgeqpf)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "dgeqr2") "C2F(dgeqr2)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "dgeqrf") "C2F(dgeqrf)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "dger") "C2F(dger)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "dgerfs") "C2F(dgerfs)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "dgerq2") "C2F(dgerq2)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "dgerqf") "C2F(dgerqf)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "dgesc2") "C2F(dgesc2)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "dgesdd") "C2F(dgesdd)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "dgesv") "C2F(dgesv)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "dgesvd") "C2F(dgesvd)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "dgesvx") "C2F(dgesvx)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "dgetc2") "C2F(dgetc2)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "dgetf2") "C2F(dgetf2)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "dgetrf") "C2F(dgetrf)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "dgetri") "C2F(dgetri)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "dgetrs") "C2F(dgetrs)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "dggbak") "C2F(dggbak)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "dggbal") "C2F(dggbal)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "dgges") "C2F(dgges)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "dggev") "C2F(dggev)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "dgghrd") "C2F(dgghrd)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "dgpadm") "C2F(dgpadm)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "dhgeqz") "C2F(dhgeqz)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "dhseqr") "C2F(dhseqr)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "dlabad") "C2F(dlabad)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "dlabrd") "C2F(dlabrd)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "dlacon") "C2F(dlacon)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "dlacpy") "C2F(dlacpy)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "dladiv") "C2F(dladiv)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "dlae2") "C2F(dlae2)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "dlaev2") "C2F(dlaev2)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "dlaexc") "C2F(dlaexc)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "dlag2") "C2F(dlag2)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "dlags2") "C2F(dlags2)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "dlagv2") "C2F(dlagv2)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "dlahqr") "C2F(dlahqr)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "dlahrd") "C2F(dlahrd)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "dlaic1") "C2F(dlaic1)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "dlaln2") "C2F(dlaln2)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "dlamc1") "C2F(dlamc1)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "dlamc2") "C2F(dlamc2)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "dlamc3") "C2F(dlamc3)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "dlamc4") "C2F(dlamc4)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "dlamc5") "C2F(dlamc5)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "dlamch") "C2F(dlamch)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "dlangb") "C2F(dlangb)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "dlange") "C2F(dlange)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "dlanhs") "C2F(dlanhs)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "dlansp") "C2F(dlansp)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "dlanst") "C2F(dlanst)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "dlansy") "C2F(dlansy)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "dlantr") "C2F(dlantr)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "dlanv2") "C2F(dlanv2)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "dlapmt") "C2F(dlapmt)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "dlapy2") "C2F(dlapy2)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "dlapy3") "C2F(dlapy3)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "dlaqge") "C2F(dlaqge)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "dlaqp2") "C2F(dlaqp2)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "dlaqps") "C2F(dlaqps)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "dlarf") "C2F(dlarf)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "dlarfb") "C2F(dlarfb)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "dlarfg") "C2F(dlarfg)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "dlarft") "C2F(dlarft)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "dlarfx") "C2F(dlarfx)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "dlartg") "C2F(dlartg)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "dlarz") "C2F(dlarz)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "dlarzb") "C2F(dlarzb)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "dlarzt") "C2F(dlarzt)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "dlas2") "C2F(dlas2)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "dlascl") "C2F(dlascl)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "dlaset") "C2F(dlaset)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "dlasq1") "C2F(dlasq1)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "dlasq2") "C2F(dlasq2)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "dlasq3") "C2F(dlasq3)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "dlasq4") "C2F(dlasq4)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "dlasr") "C2F(dlasr)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "dlasrt") "C2F(dlasrt)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "dlassq") "C2F(dlassq)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "dlasv2") "C2F(dlasv2)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "dlaswp") "C2F(dlaswp)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "dlasy2") "C2F(dlasy2)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "dlasyf") "C2F(dlasyf)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "dlatdf") "C2F(dlatdf)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "dlatrd") "C2F(dlatrd)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "dlatrs") "C2F(dlatrs)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "dlatrz") "C2F(dlatrz)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "dlatzm") "C2F(dlatzm)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "dnrm2") "C2F(dnrm2)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "dopgtr") "C2F(dopgtr)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "dorg2l") "C2F(dorg2l)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "dorg2r") "C2F(dorg2r)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "dorgbr") "C2F(dorgbr)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "dorghr") "C2F(dorghr)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "dorgl2") "C2F(dorgl2)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "dorglq") "C2F(dorglq)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "dorgql") "C2F(dorgql)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "dorgqr") "C2F(dorgqr)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "dorgr2") "C2F(dorgr2)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "dorgrq") "C2F(dorgrq)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "dorgtr") "C2F(dorgtr)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "dorm2l") "C2F(dorm2l)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "dorm2r") "C2F(dorm2r)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "dormbr") "C2F(dormbr)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "dormhr") "C2F(dormhr)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "dorml2") "C2F(dorml2)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "dormlq") "C2F(dormlq)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "dormql") "C2F(dormql)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "dormqr") "C2F(dormqr)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "dormr2") "C2F(dormr2)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "dormr3") "C2F(dormr3)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "dormrq") "C2F(dormrq)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "dormrz") "C2F(dormrz)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "dpocon") "C2F(dpocon)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "dpotf2") "C2F(dpotf2)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "dpotrf") "C2F(dpotrf)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "dpotrs") "C2F(dpotrs)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "dpptrf") "C2F(dpptrf)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "drotg") "C2F(drotg)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "drot") "C2F(drot)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "drscl") "C2F(drscl)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "dsbmv") "C2F(dsbmv)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "dscal") "C2F(dscal)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "dspadm") "C2F(dspadm)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "dspev") "C2F(dspev)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "dspgst") "C2F(dspgst)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "dspgv") "C2F(dspgv)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "dspmv") "C2F(dspmv)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "dspr") "C2F(dspr)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "dspr2") "C2F(dspr2)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "dsptrd") "C2F(dsptrd)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "dsptrf") "C2F(dsptrf)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "dsteqr") "C2F(dsteqr)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "dsterf") "C2F(dsterf)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "dswap") "C2F(dswap)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "dsycon") "C2F(dsycon)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "dsyev") "C2F(dsyev)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "dsyevr") "C2F(dsyevr)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "dsymm") "C2F(dsymm)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "dsymv") "C2F(dsymv)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "dsyr") "C2F(dsyr)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "dsyr2") "C2F(dsyr2)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "dsyr2k") "C2F(dsyr2k)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "dsyrk") "C2F(dsyrk)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "dsysv") "C2F(dsysv)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "dsytd2") "C2F(dsytd2)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "dsytf2") "C2F(dsytf2)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "dsytrd") "C2F(dsytrd)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "dsytrf") "C2F(dsytrf)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "dsytri") "C2F(dsytri)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "dsytrs") "C2F(dsytrs)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "dtbmv") "C2F(dtbmv)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "dtbsv") "C2F(dtbsv)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "dtgevc") "C2F(dtgevc)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "dtgex2") "C2F(dtgex2)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "dtgexc") "C2F(dtgexc)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "dtgsen") "C2F(dtgsen)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "dtgsy2") "C2F(dtgsy2)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "dtgsyl") "C2F(dtgsyl)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "dtpmv") "C2F(dtpmv)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "dtpsv") "C2F(dtpsv)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "dtrcon") "C2F(dtrcon)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "dtrevc") "C2F(dtrevc)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "dtrexc") "C2F(dtrexc)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "dtrmm") "C2F(dtrmm)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "dtrmv") "C2F(dtrmv)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "dtrsen") "C2F(dtrsen)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "dtrsm") "C2F(dtrsm)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "dtrsv") "C2F(dtrsv)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "dtrsyl") "C2F(dtrsyl)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "dtrti2") "C2F(dtrti2)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "dtrtri") "C2F(dtrtri)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "dtrtrs") "C2F(dtrtrs)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "dtzrqf") "C2F(dtzrqf)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "dtzrzf") "C2F(dtzrzf)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "dzasum") "C2F(dzasum)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "dznrm2") "C2F(dznrm2)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "dzsum1") "C2F(dzsum1)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "idamax") "C2F(idamax)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "ilaenv") "C2F(ilaenv)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "izamax") "C2F(izamax)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "izmax1") "C2F(izmax1)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "lsame") "C2F(lsame)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "lsame") "C2F(lsame)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "slamc1") "C2F(slamc1)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "slamc2") "C2F(slamc2)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "slamc3") "C2F(slamc3)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "slamc4") "C2F(slamc4)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "slamc5") "C2F(slamc5)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "slamch") "C2F(slamch)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "xerbla") "C2F(xerbla)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "xerbla") "C2F(xerbla)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "zaxpy") "C2F(zaxpy)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "zbdsqr") "C2F(zbdsqr)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "zcopy") "C2F(zcopy)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "zdotc") "C2F(zdotc)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "zdotc") "C2F(zdotc)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "zdotu") "C2F(zdotu)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "zdotu") "C2F(zdotu)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "zdrot") "C2F(zdrot)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "zdrscl") "C2F(zdrscl)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "zdscal") "C2F(zdscal)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "zgbcon") "C2F(zgbcon)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "zgbmv") "C2F(zgbmv)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "zgbsv") "C2F(zgbsv)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "zgbtrf") "C2F(zgbtrf)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "zgbtrs") "C2F(zgbtrs)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "zgebak") "C2F(zgebak)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "zgebal") "C2F(zgebal)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "zgebd2") "C2F(zgebd2)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "zgebrd") "C2F(zgebrd)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "zgecon") "C2F(zgecon)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "zgees") "C2F(zgees)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "zgeev") "C2F(zgeev)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "zgehd2") "C2F(zgehd2)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "zgehrd") "C2F(zgehrd)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "zgelq2") "C2F(zgelq2)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "zgelqf") "C2F(zgelqf)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "zgelsd") "C2F(zgelsd)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "zgelsy") "C2F(zgelsy)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "zgemm") "C2F(zgemm)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "zgemv") "C2F(zgemv)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "zgeqp3") "C2F(zgeqp3)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "zgeqpf") "C2F(zgeqpf)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "zgeqr2") "C2F(zgeqr2)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "zgeqrf") "C2F(zgeqrf)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "zgerc") "C2F(zgerc)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "zgeru") "C2F(zgeru)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "zgesc2") "C2F(zgesc2)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "zgesdd") "C2F(zgesdd)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "zgesvd") "C2F(zgesvd)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "zgetc2") "C2F(zgetc2)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "zgetf2") "C2F(zgetf2)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "zgetrf") "C2F(zgetrf)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "zgetri") "C2F(zgetri)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "zgetrs") "C2F(zgetrs)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "zggbak") "C2F(zggbak)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "zggbal") "C2F(zggbal)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "zgges") "C2F(zgges)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "zggev") "C2F(zggev)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "zgghrd") "C2F(zgghrd)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "zgpadm") "C2F(zgpadm)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "zhbmv") "C2F(zhbmv)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "zheev") "C2F(zheev)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "zheevr") "C2F(zheevr)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "zhemm") "C2F(zhemm)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "zhemv") "C2F(zhemv)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "zher") "C2F(zher)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "zher2") "C2F(zher2)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "zher2k") "C2F(zher2k)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "zherk") "C2F(zherk)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "zhetd2") "C2F(zhetd2)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "zhetrd") "C2F(zhetrd)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "zhgeqz") "C2F(zhgeqz)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "zhpadm") "C2F(zhpadm)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "zhpmv") "C2F(zhpmv)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "zhpr") "C2F(zhpr)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "zhpr2") "C2F(zhpr2)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "zhseqr") "C2F(zhseqr)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "zlabrd") "C2F(zlabrd)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "zlacgv") "C2F(zlacgv)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "zlacon") "C2F(zlacon)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "zlacpy") "C2F(zlacpy)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "zladiv") "C2F(zladiv)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "zlahqr") "C2F(zlahqr)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "zlahrd") "C2F(zlahrd)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "zlaic1") "C2F(zlaic1)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "zlangb") "C2F(zlangb)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "zlange") "C2F(zlange)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "zlanhe") "C2F(zlanhe)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "zlanhs") "C2F(zlanhs)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "zlaqp2") "C2F(zlaqp2)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "zlaqps") "C2F(zlaqps)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "zlarf") "C2F(zlarf)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "zlarfb") "C2F(zlarfb)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "zlarfg") "C2F(zlarfg)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "zlarft") "C2F(zlarft)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "zlarfx") "C2F(zlarfx)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "zlartg") "C2F(zlartg)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "zlarz") "C2F(zlarz)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "zlarzb") "C2F(zlarzb)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "zlarzt") "C2F(zlarzt)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "zlascl") "C2F(zlascl)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "zlaset") "C2F(zlaset)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "zlasr") "C2F(zlasr)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "zlassq") "C2F(zlassq)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "zlaswp") "C2F(zlaswp)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "zlatdf") "C2F(zlatdf)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "zlatrd") "C2F(zlatrd)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "zlatrs") "C2F(zlatrs)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "zlatrz") "C2F(zlatrz)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "zpocon") "C2F(zpocon)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "zpotf2") "C2F(zpotf2)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "zpotrf") "C2F(zpotrf)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "zpotrs") "C2F(zpotrs)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "zrot") "C2F(zrot)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "zrotg") "C2F(zrotg)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "zscal") "C2F(zscal)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "zsteqr") "C2F(zsteqr)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "zswap") "C2F(zswap)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "zsycon") "C2F(zsycon)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "zsymm") "C2F(zsymm)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "zsyr2k") "C2F(zsyr2k)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "zsyrk") "C2F(zsyrk)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "zsytrf") "C2F(zsytrf)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "zsytrs") "C2F(zsytrs)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "ztbmv") "C2F(ztbmv)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "ztbsv") "C2F(ztbsv)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "ztgevc") "C2F(ztgevc)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "ztgex2") "C2F(ztgex2)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "ztgexc") "C2F(ztgexc)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "ztgsen") "C2F(ztgsen)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "ztgsy2") "C2F(ztgsy2)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "ztgsyl") "C2F(ztgsyl)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "ztpmv") "C2F(ztpmv)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "ztpsv") "C2F(ztpsv)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "ztrcon") "C2F(ztrcon)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "ztrevc") "C2F(ztrevc)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "ztrexc") "C2F(ztrexc)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "ztrmm") "C2F(ztrmm)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "ztrmv") "C2F(ztrmv)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "ztrsen") "C2F(ztrsen)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "ztrsm") "C2F(ztrsm)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "ztrsv") "C2F(ztrsv)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "ztrsyl") "C2F(ztrsyl)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "ztrti2") "C2F(ztrti2)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "ztrtri") "C2F(ztrtri)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "ztrtrs") "C2F(ztrtrs)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "ztzrzf") "C2F(ztzrzf)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "zung2l") "C2F(zung2l)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "zung2r") "C2F(zung2r)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "zungbr") "C2F(zungbr)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "zunghr") "C2F(zunghr)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "zungl2") "C2F(zungl2)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "zunglq") "C2F(zunglq)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "zungql") "C2F(zungql)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "zungqr") "C2F(zungqr)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "zungtr") "C2F(zungtr)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "zunm2r") "C2F(zunm2r)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "zunmbr") "C2F(zunmbr)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "zunml2") "C2F(zunml2)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "zunmlq") "C2F(zunmlq)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "zunmqr") "C2F(zunmqr)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "zunmr3") "C2F(zunmr3)")
  (goto-char (point-min))
  (replace-regexp (concat prefix "zunmrz") "C2F(zunmrz)")
)

(defun job () 
  (test)
  (save-buffer)
  )


