(defun test ()
  (goto-char (point-min))
  (setq prefix "nsp_ctrlpack_" )
  (replace-regexp (concat prefix "dasum") "nsp_calpack_dasum")
  (replace-regexp (concat prefix "arcosh") "nsp_calpack_arcosh" )
  (goto-char (point-min))
  (replace-regexp (concat prefix "arsinh") "nsp_calpack_arsinh" )
  (goto-char (point-min))
  (replace-regexp (concat prefix "basout") "nsp_calpack_basout" )
  (goto-char (point-min))
  (replace-regexp (concat prefix "bchfac") "nsp_calpack_bchfac" )
  (goto-char (point-min))
  (replace-regexp (concat prefix "bchslv") "nsp_calpack_bchslv" )
  (goto-char (point-min))
  (replace-regexp (concat prefix "bicubicinterp") "nsp_calpack_bicubicinterp" )
  (goto-char (point-min))
  (replace-regexp (concat prefix "bicubicinterpwithgrad") "nsp_calpack_bicubicinterpwithgrad" )
  (goto-char (point-min))
  (replace-regexp (concat prefix "bicubicinterpwithgradandhes") "nsp_calpack_bicubicinterpwithgradandhes" )
  (goto-char (point-min))
  (replace-regexp (concat prefix "bicubicspline") "nsp_calpack_bicubicspline" )
  (goto-char (point-min))
  (replace-regexp (concat prefix "bicubicsubspline") "nsp_calpack_bicubicsubspline" )
  (goto-char (point-min))
  (replace-regexp (concat prefix "bslsq") "nsp_calpack_bslsq" )
  (goto-char (point-min))
  (replace-regexp (concat prefix "bspp") "nsp_calpack_bspp" )
  (goto-char (point-min))
  (replace-regexp (concat prefix "bspvb") "nsp_calpack_bspvb" )
  (goto-char (point-min))
  (replace-regexp (concat prefix "calerf") "nsp_calpack_calerf" )
  (goto-char (point-min))
  (replace-regexp (concat prefix "ccopy") "nsp_calpack_ccopy" )
  (goto-char (point-min))
  (replace-regexp (concat prefix "coshin") "nsp_calpack_coshin" )
  (goto-char (point-min))
  (replace-regexp (concat prefix "cs2grd") "nsp_calpack_cs2grd" )
  (goto-char (point-min))
  (replace-regexp (concat prefix "cs2hes") "nsp_calpack_cs2hes" )
  (goto-char (point-min))
  (replace-regexp (concat prefix "cs2val") "nsp_calpack_cs2val" )
  (goto-char (point-min))
  (replace-regexp (concat prefix "cshep2") "nsp_calpack_cshep2" )
  (goto-char (point-min))
  (replace-regexp (concat prefix "cupro") "nsp_calpack_cupro" )
  (goto-char (point-min))
  (replace-regexp (concat prefix "cuproi") "nsp_calpack_cuproi" )
  (goto-char (point-min))
  (replace-regexp (concat prefix "cusum") "nsp_calpack_cusum" )
  (goto-char (point-min))
  (replace-regexp (concat prefix "cyclictridiagldltsolve") "nsp_calpack_cyclictridiagldltsolve" )
  (goto-char (point-min))
  (replace-regexp (concat prefix "d1mach") "nsp_calpack_d1mach" )
  (goto-char (point-min))
  (replace-regexp (concat prefix "d9b0mp") "nsp_calpack_d9b0mp" )
  (goto-char (point-min))
  (replace-regexp (concat prefix "d9b1mp") "nsp_calpack_d9b1mp" )
  (goto-char (point-min))
  (replace-regexp (concat prefix "d9knus") "nsp_calpack_d9knus" )
  (goto-char (point-min))
  (replace-regexp (concat prefix "d9lgmc") "nsp_calpack_d9lgmc" )
  (goto-char (point-min))
  (replace-regexp (concat prefix "dad") "nsp_calpack_dad" )
  (goto-char (point-min))
  (replace-regexp (concat prefix "dadd") "nsp_calpack_dadd" )
  (goto-char (point-min))
  (replace-regexp (concat prefix "dasyik") "nsp_calpack_dasyik" )
  (goto-char (point-min))
  (replace-regexp (concat prefix "dasyjy") "nsp_calpack_dasyjy" )
  (goto-char (point-min))
  (replace-regexp (concat prefix "db3ink") "nsp_calpack_db3ink" )
  (goto-char (point-min))
  (replace-regexp (concat prefix "db3val") "nsp_calpack_db3val" )
  (goto-char (point-min))
  (replace-regexp (concat prefix "dbdiff") "nsp_calpack_dbdiff" )
  (goto-char (point-min))
  (replace-regexp (concat prefix "dbesi") "nsp_calpack_dbesi" )
  (goto-char (point-min))
  (replace-regexp (concat prefix "dbesi0") "nsp_calpack_dbesi0" )
  (goto-char (point-min))
  (replace-regexp (concat prefix "dbesi1") "nsp_calpack_dbesi1" )
  (goto-char (point-min))
  (replace-regexp (concat prefix "dbesig") "nsp_calpack_dbesig" )
  (goto-char (point-min))
  (replace-regexp (concat prefix "dbesiv") "nsp_calpack_dbesiv" )
  (goto-char (point-min))
  (replace-regexp (concat prefix "dbesj") "nsp_calpack_dbesj" )
  (goto-char (point-min))
  (replace-regexp (concat prefix "dbesj0") "nsp_calpack_dbesj0" )
  (goto-char (point-min))
  (replace-regexp (concat prefix "dbesj1") "nsp_calpack_dbesj1" )
  (goto-char (point-min))
  (replace-regexp (concat prefix "dbesjg") "nsp_calpack_dbesjg" )
  (goto-char (point-min))
  (replace-regexp (concat prefix "dbesjv") "nsp_calpack_dbesjv" )
  (goto-char (point-min))
  (replace-regexp (concat prefix "dbesk") "nsp_calpack_dbesk" )
  (goto-char (point-min))
  (replace-regexp (concat prefix "dbesk0") "nsp_calpack_dbesk0" )
  (goto-char (point-min))
  (replace-regexp (concat prefix "dbesk1") "nsp_calpack_dbesk1" )
  (goto-char (point-min))
  (replace-regexp (concat prefix "dbeskg") "nsp_calpack_dbeskg" )
  (goto-char (point-min))
  (replace-regexp (concat prefix "dbesks") "nsp_calpack_dbesks" )
  (goto-char (point-min))
  (replace-regexp (concat prefix "dbeskv") "nsp_calpack_dbeskv" )
  (goto-char (point-min))
  (replace-regexp (concat prefix "dbesy") "nsp_calpack_dbesy" )
  (goto-char (point-min))
  (replace-regexp (concat prefix "dbesy0") "nsp_calpack_dbesy0" )
  (goto-char (point-min))
  (replace-regexp (concat prefix "dbesy1") "nsp_calpack_dbesy1" )
  (goto-char (point-min))
  (replace-regexp (concat prefix "dbesyg") "nsp_calpack_dbesyg" )
  (goto-char (point-min))
  (replace-regexp (concat prefix "dbesyv") "nsp_calpack_dbesyv" )
  (goto-char (point-min))
  (replace-regexp (concat prefix "dbintk") "nsp_calpack_dbintk" )
  (goto-char (point-min))
  (replace-regexp (concat prefix "dbkias") "nsp_calpack_dbkias" )
  (goto-char (point-min))
  (replace-regexp (concat prefix "dbkisr") "nsp_calpack_dbkisr" )
  (goto-char (point-min))
  (replace-regexp (concat prefix "dbknot") "nsp_calpack_dbknot" )
  (goto-char (point-min))
  (replace-regexp (concat prefix "dbnfac") "nsp_calpack_dbnfac" )
  (goto-char (point-min))
  (replace-regexp (concat prefix "dbnslv") "nsp_calpack_dbnslv" )
  (goto-char (point-min))
  (replace-regexp (concat prefix "dbsi0e") "nsp_calpack_dbsi0e" )
  (goto-char (point-min))
  (replace-regexp (concat prefix "dbsi1e") "nsp_calpack_dbsi1e" )
  (goto-char (point-min))
  (replace-regexp (concat prefix "dbsk0e") "nsp_calpack_dbsk0e" )
  (goto-char (point-min))
  (replace-regexp (concat prefix "dbsk1e") "nsp_calpack_dbsk1e" )
  (goto-char (point-min))
  (replace-regexp (concat prefix "dbskes") "nsp_calpack_dbskes" )
  (goto-char (point-min))
  (replace-regexp (concat prefix "dbskin") "nsp_calpack_dbskin" )
  (goto-char (point-min))
  (replace-regexp (concat prefix "dbsknu") "nsp_calpack_dbsknu" )
  (goto-char (point-min))
  (replace-regexp (concat prefix "dbspvn") "nsp_calpack_dbspvn" )
  (goto-char (point-min))
  (replace-regexp (concat prefix "dbsynu") "nsp_calpack_dbsynu" )
  (goto-char (point-min))
  (replace-regexp (concat prefix "dbtpcf") "nsp_calpack_dbtpcf" )
  (goto-char (point-min))
  (replace-regexp (concat prefix "dbvalu") "nsp_calpack_dbvalu" )
  (goto-char (point-min))
  (replace-regexp (concat prefix "dcsevl") "nsp_calpack_dcsevl" )
  (goto-char (point-min))
  (replace-regexp (concat prefix "ddif") "nsp_calpack_ddif" )
  (goto-char (point-min))
  (replace-regexp (concat prefix "ddpow") "nsp_calpack_ddpow" )
  (goto-char (point-min))
  (replace-regexp (concat prefix "ddpow1") "nsp_calpack_ddpow1" )
  (goto-char (point-min))
  (replace-regexp (concat prefix "ddpowe") "nsp_calpack_ddpowe" )
  (goto-char (point-min))
  (replace-regexp (concat prefix "ddrdiv") "nsp_calpack_ddrdiv" )
  (goto-char (point-min))
  (replace-regexp (concat prefix "derfcf") "nsp_calpack_derfcf" )
  (goto-char (point-min))
  (replace-regexp (concat prefix "derfcx") "nsp_calpack_derfcx" )
  (goto-char (point-min))
  (replace-regexp (concat prefix "derff") "nsp_calpack_derff" )
  (goto-char (point-min))
  (replace-regexp (concat prefix "derivd") "nsp_calpack_derivd" )
  (goto-char (point-min))
  (replace-regexp (concat prefix "dexint") "nsp_calpack_dexint" )
  (goto-char (point-min))
  (replace-regexp (concat prefix "dgamlm") "nsp_calpack_dgamlm" )
  (goto-char (point-min))
  (replace-regexp (concat prefix "dgamln") "nsp_calpack_dgamln" )
  (goto-char (point-min))
  (replace-regexp (concat prefix "dgamma") "nsp_calpack_dgamma" )
  (goto-char (point-min))
  (replace-regexp (concat prefix "dgammacody") "nsp_calpack_dgammacody" )
  (goto-char (point-min))
  (replace-regexp (concat prefix "dgamrn") "nsp_calpack_dgamrn" )
  (goto-char (point-min))
  (replace-regexp (concat prefix "dhkseq") "nsp_calpack_dhkseq" )
  (goto-char (point-min))
  (replace-regexp (concat prefix "dintrv") "nsp_calpack_dintrv" )
  (goto-char (point-min))
  (replace-regexp (concat prefix "dipow") "nsp_calpack_dipow" )
  (goto-char (point-min))
  (replace-regexp (concat prefix "dipowe") "nsp_calpack_dipowe" )
  (goto-char (point-min))
  (replace-regexp (concat prefix "djairy") "nsp_calpack_djairy" )
  (goto-char (point-min))
  (replace-regexp (concat prefix "dlblks") "nsp_calpack_dlblks" )
  (goto-char (point-min))
  (replace-regexp (concat prefix "dlgama") "nsp_calpack_dlgama" )
  (goto-char (point-min))
  (replace-regexp (concat prefix "dlngam") "nsp_calpack_dlngam" )
  (goto-char (point-min))
  (replace-regexp (concat prefix "dmcopy") "nsp_calpack_dmcopy" )
  (goto-char (point-min))
  (replace-regexp (concat prefix "dmmul") "nsp_calpack_dmmul" )
  (goto-char (point-min))
  (replace-regexp (concat prefix "dmmul1") "nsp_calpack_dmmul1" )
  (goto-char (point-min))
  (replace-regexp (concat prefix "dmprod") "nsp_calpack_dmprod" )
  (goto-char (point-min))
  (replace-regexp (concat prefix "dmsum") "nsp_calpack_dmsum" )
  (goto-char (point-min))
  (replace-regexp (concat prefix "dpchim") "nsp_calpack_dpchim" )
  (goto-char (point-min))
  (replace-regexp (concat prefix "dpchst") "nsp_calpack_dpchst" )
  (goto-char (point-min))
  (replace-regexp (concat prefix "dpsixn") "nsp_calpack_dpsixn" )
  (goto-char (point-min))
  (replace-regexp (concat prefix "drdiv") "nsp_calpack_drdiv" )
  (goto-char (point-min))
  (replace-regexp (concat prefix "driverdb3val") "nsp_calpack_driverdb3val" )
  (goto-char (point-min))
  (replace-regexp (concat prefix "driverdb3valwithgrad") "nsp_calpack_driverdb3valwithgrad" )
  (goto-char (point-min))
  (replace-regexp (concat prefix "dsearchc") "nsp_calpack_dsearchc" )
  (goto-char (point-min))
  (replace-regexp (concat prefix "dsearchd") "nsp_calpack_dsearchd" )
  (goto-char (point-min))
  (replace-regexp (concat prefix "dset") "nsp_calpack_dset" )
  (goto-char (point-min))
  (replace-regexp (concat prefix "dsort") "nsp_calpack_dsort" )
  (goto-char (point-min))
  (replace-regexp (concat prefix "dsum") "nsp_calpack_dsum" )
  (goto-char (point-min))
  (replace-regexp (concat prefix "dtild") "nsp_calpack_dtild" )
  (goto-char (point-min))
  (replace-regexp (concat prefix "dvmul") "nsp_calpack_dvmul" )
  (goto-char (point-min))
  (replace-regexp (concat prefix "dwdiv") "nsp_calpack_dwdiv" )
  (goto-char (point-min))
  (replace-regexp (concat prefix "dwpow") "nsp_calpack_dwpow" )
  (goto-char (point-min))
  (replace-regexp (concat prefix "dwpow1") "nsp_calpack_dwpow1" )
  (goto-char (point-min))
  (replace-regexp (concat prefix "dwpowe") "nsp_calpack_dwpowe" )
  (goto-char (point-min))
  (replace-regexp (concat prefix "dwrdiv") "nsp_calpack_dwrdiv" )
  (goto-char (point-min))
  (replace-regexp (concat prefix "dxadd") "nsp_calpack_dxadd" )
  (goto-char (point-min))
  (replace-regexp (concat prefix "dxadj") "nsp_calpack_dxadj" )
  (goto-char (point-min))
  (replace-regexp (concat prefix "dxlegf") "nsp_calpack_dxlegf" )
  (goto-char (point-min))
  (replace-regexp (concat prefix "dxpmu") "nsp_calpack_dxpmu" )
  (goto-char (point-min))
  (replace-regexp (concat prefix "dxpmup") "nsp_calpack_dxpmup" )
  (goto-char (point-min))
  (replace-regexp (concat prefix "dxpnrm") "nsp_calpack_dxpnrm" )
  (goto-char (point-min))
  (replace-regexp (concat prefix "dxpqnu") "nsp_calpack_dxpqnu" )
  (goto-char (point-min))
  (replace-regexp (concat prefix "dxpsi") "nsp_calpack_dxpsi" )
  (goto-char (point-min))
  (replace-regexp (concat prefix "dxqmu") "nsp_calpack_dxqmu" )
  (goto-char (point-min))
  (replace-regexp (concat prefix "dxqnu") "nsp_calpack_dxqnu" )
  (goto-char (point-min))
  (replace-regexp (concat prefix "dxred") "nsp_calpack_dxred" )
  (goto-char (point-min))
  (replace-regexp (concat prefix "dxset") "nsp_calpack_dxset" )
  (goto-char (point-min))
  (replace-regexp (concat prefix "dyairy") "nsp_calpack_dyairy" )
  (goto-char (point-min))
  (replace-regexp (concat prefix "entier") "nsp_calpack_entier" )
  (goto-char (point-min))
  (replace-regexp (concat prefix "evalbicubic") "nsp_calpack_evalbicubic" )
  (goto-char (point-min))
  (replace-regexp (concat prefix "evalhermite") "nsp_calpack_evalhermite" )
  (goto-char (point-min))
  (replace-regexp (concat prefix "evalpwhermite") "nsp_calpack_evalpwhermite" )
  (goto-char (point-min))
  (replace-regexp (concat prefix "fdump") "nsp_calpack_fdump" )
  (goto-char (point-min))
  (replace-regexp (concat prefix "franck") "nsp_calpack_franck" )
  (goto-char (point-min))
  (replace-regexp (concat prefix "gdcp2i") "nsp_calpack_gdcp2i" )
  (goto-char (point-min))
  (replace-regexp (concat prefix "getnp2") "nsp_calpack_getnp2" )
  (goto-char (point-min))
  (replace-regexp (concat prefix "givens") "nsp_calpack_givens" )
  (goto-char (point-min))
  (replace-regexp (concat prefix "hilber") "nsp_calpack_hilber" )
  (goto-char (point-min))
  (replace-regexp (concat prefix "i1mach") "nsp_calpack_i1mach" )
  (goto-char (point-min))
  (replace-regexp (concat prefix "icopy") "nsp_calpack_icopy" )
  (goto-char (point-min))
  (replace-regexp (concat prefix "idmax") "nsp_calpack_idmax" )
  (goto-char (point-min))
  (replace-regexp (concat prefix "idmin") "nsp_calpack_idmin" )
  (goto-char (point-min))
  (replace-regexp (concat prefix "imcopy") "nsp_calpack_imcopy" )
  (goto-char (point-min))
  (replace-regexp (concat prefix "infinity") "nsp_calpack_infinity" )
  (goto-char (point-min))
  (replace-regexp (concat prefix "initds") "nsp_calpack_initds" )
  (goto-char (point-min))
  (replace-regexp (concat prefix "int2db") "nsp_calpack_int2db" )
  (goto-char (point-min))
  (replace-regexp (concat prefix "intp") "nsp_calpack_intp" )
  (goto-char (point-min))
  (replace-regexp (concat prefix "isearch") "nsp_calpack_isearch" )
  (goto-char (point-min))
  (replace-regexp (concat prefix "iset") "nsp_calpack_iset" )
  (goto-char (point-min))
  (replace-regexp (concat prefix "isort") "nsp_calpack_isort" )
  (goto-char (point-min))
  (replace-regexp (concat prefix "isova0") "nsp_calpack_isova0" )
  (goto-char (point-min))
  (replace-regexp (concat prefix "isoval") "nsp_calpack_isoval" )
  (goto-char (point-min))
  (replace-regexp (concat prefix "ivimp") "nsp_calpack_ivimp" )
  (goto-char (point-min))
  (replace-regexp (concat prefix "iwamax") "nsp_calpack_iwamax" )
  (goto-char (point-min))
  (replace-regexp (concat prefix "j4save") "nsp_calpack_j4save" )
  (goto-char (point-min))
  (replace-regexp (concat prefix "kronc") "nsp_calpack_kronc" )
  (goto-char (point-min))
  (replace-regexp (concat prefix "kronr") "nsp_calpack_kronr" )
  (goto-char (point-min))
  (replace-regexp (concat prefix "lnblnk") "nsp_calpack_lnblnk" )
  (goto-char (point-min))
  (replace-regexp (concat prefix "lnp1m1") "nsp_calpack_lnp1m1" )
  (goto-char (point-min))
  (replace-regexp (concat prefix "logp1") "nsp_calpack_logp1" )
  (goto-char (point-min))
  (replace-regexp (concat prefix "magic") "nsp_calpack_magic" )
  (goto-char (point-min))
  (replace-regexp (concat prefix "modtest") "nsp_calpack_modtest" )
  (goto-char (point-min))
  (replace-regexp (concat prefix "mtran") "nsp_calpack_mtran" )
  (goto-char (point-min))
  (replace-regexp (concat prefix "nearfloat") "nsp_calpack_nearfloat" )
  (goto-char (point-min))
  (replace-regexp (concat prefix "psi") "nsp_calpack_psi" )
  (goto-char (point-min))
  (replace-regexp (concat prefix "pythag") "nsp_calpack_pythag" )
  (goto-char (point-min))
  (replace-regexp (concat prefix "rat") "nsp_calpack_rat" )
  (goto-char (point-min))
  (replace-regexp (concat prefix "rcopy") "nsp_calpack_rcopy" )
  (goto-char (point-min))
  (replace-regexp (concat prefix "rcsort") "nsp_calpack_rcsort" )
  (goto-char (point-min))
  (replace-regexp (concat prefix "rea2db") "nsp_calpack_rea2db" )
  (goto-char (point-min))
  (replace-regexp (concat prefix "ribesl") "nsp_calpack_ribesl" )
  (goto-char (point-min))
  (replace-regexp (concat prefix "rjbesl") "nsp_calpack_rjbesl" )
  (goto-char (point-min))
  (replace-regexp (concat prefix "rkbesl") "nsp_calpack_rkbesl" )
  (goto-char (point-min))
  (replace-regexp (concat prefix "rotate") "nsp_calpack_rotate" )
  (goto-char (point-min))
  (replace-regexp (concat prefix "rptest") "nsp_calpack_rptest" )
  (goto-char (point-min))
  (replace-regexp (concat prefix "rybesl") "nsp_calpack_rybesl" )
  (goto-char (point-min))
  (replace-regexp (concat prefix "scidcopy") "nsp_calpack_scidcopy" )
  (goto-char (point-min))
  (replace-regexp (concat prefix "sciround") "nsp_calpack_sciround" )
  (goto-char (point-min))
  (replace-regexp (concat prefix "setup2") "nsp_calpack_setup2" )
  (goto-char (point-min))
  (replace-regexp (concat prefix "simple") "nsp_calpack_simple" )
  (goto-char (point-min))
  (replace-regexp (concat prefix "spfit") "nsp_calpack_spfit" )
  (goto-char (point-min))
  (replace-regexp (concat prefix "splinecub") "nsp_calpack_splinecub" )
  (goto-char (point-min))
  (replace-regexp (concat prefix "store2") "nsp_calpack_store2" )
  (goto-char (point-min))
  (replace-regexp (concat prefix "tridiagldltsolve") "nsp_calpack_tridiagldltsolve" )
  (goto-char (point-min))
  (replace-regexp (concat prefix "unsfdcopy") "nsp_calpack_unsfdcopy" )
  (goto-char (point-min))
  (replace-regexp (concat prefix "urand") "nsp_calpack_urand" )
  (goto-char (point-min))
  (replace-regexp (concat prefix "vpythag") "nsp_calpack_vpythag" )
  (goto-char (point-min))
  (replace-regexp (concat prefix "wacos") "nsp_calpack_wacos" )
  (goto-char (point-min))
  (replace-regexp (concat prefix "wasin") "nsp_calpack_wasin" )
  (goto-char (point-min))
  (replace-regexp (concat prefix "wasum") "nsp_calpack_wasum" )
  (goto-char (point-min))
  (replace-regexp (concat prefix "watan") "nsp_calpack_watan" )
  (goto-char (point-min))
  (replace-regexp (concat prefix "waxpy") "nsp_calpack_waxpy" )
  (goto-char (point-min))
  (replace-regexp (concat prefix "wcopy") "nsp_calpack_wcopy" )
  (goto-char (point-min))
  (replace-regexp (concat prefix "wddiv") "nsp_calpack_wddiv" )
  (goto-char (point-min))
  (replace-regexp (concat prefix "wdiv") "nsp_calpack_wdiv" )
  (goto-char (point-min))
  (replace-regexp (concat prefix "wdotci") "nsp_calpack_wdotci" )
  (goto-char (point-min))
  (replace-regexp (concat prefix "wdotcr") "nsp_calpack_wdotcr" )
  (goto-char (point-min))
  (replace-regexp (concat prefix "wdpow") "nsp_calpack_wdpow" )
  (goto-char (point-min))
  (replace-regexp (concat prefix "wdpow1") "nsp_calpack_wdpow1" )
  (goto-char (point-min))
  (replace-regexp (concat prefix "wdpowe") "nsp_calpack_wdpowe" )
  (goto-char (point-min))
  (replace-regexp (concat prefix "wdrdiv") "nsp_calpack_wdrdiv" )
  (goto-char (point-min))
  (replace-regexp (concat prefix "wipow") "nsp_calpack_wipow" )
  (goto-char (point-min))
  (replace-regexp (concat prefix "wipowe") "nsp_calpack_wipowe" )
  (goto-char (point-min))
  (replace-regexp (concat prefix "wlog") "nsp_calpack_wlog" )
  (goto-char (point-min))
  (replace-regexp (concat prefix "wmmul") "nsp_calpack_wmmul" )
  (goto-char (point-min))
  (replace-regexp (concat prefix "wmprod") "nsp_calpack_wmprod" )
  (goto-char (point-min))
  (replace-regexp (concat prefix "wmsum") "nsp_calpack_wmsum" )
  (goto-char (point-min))
  (replace-regexp (concat prefix "wmul") "nsp_calpack_wmul" )
  (goto-char (point-min))
  (replace-regexp (concat prefix "wnrm2") "nsp_calpack_wnrm2" )
  (goto-char (point-min))
  (replace-regexp (concat prefix "wrscal") "nsp_calpack_wrscal" )
  (goto-char (point-min))
  (replace-regexp (concat prefix "wscal") "nsp_calpack_wscal" )
  (goto-char (point-min))
  (replace-regexp (concat prefix "wsign") "nsp_calpack_wsign" )
  (goto-char (point-min))
  (replace-regexp (concat prefix "wsort") "nsp_calpack_wsort" )
  (goto-char (point-min))
  (replace-regexp (concat prefix "wsqrt") "nsp_calpack_wsqrt" )
  (goto-char (point-min))
  (replace-regexp (concat prefix "wswap") "nsp_calpack_wswap" )
  (goto-char (point-min))
  (replace-regexp (concat prefix "wtan") "nsp_calpack_wtan" )
  (goto-char (point-min))
  (replace-regexp (concat prefix "wvmul") "nsp_calpack_wvmul" )
  (goto-char (point-min))
  (replace-regexp (concat prefix "wwdiv") "nsp_calpack_wwdiv" )
  (goto-char (point-min))
  (replace-regexp (concat prefix "wwpow") "nsp_calpack_wwpow" )
  (goto-char (point-min))
  (replace-regexp (concat prefix "wwpow1") "nsp_calpack_wwpow1" )
  (goto-char (point-min))
  (replace-regexp (concat prefix "wwpowe") "nsp_calpack_wwpowe" )
  (goto-char (point-min))
  (replace-regexp (concat prefix "wwrdiv") "nsp_calpack_wwrdiv" )
  (goto-char (point-min))
  (replace-regexp (concat prefix "xercnt") "nsp_calpack_xercnt" )
  (goto-char (point-min))
  (replace-regexp (concat prefix "xerhlt") "nsp_calpack_xerhlt" )
  (goto-char (point-min))
  (replace-regexp (concat prefix "xermsg") "nsp_calpack_xermsg" )
  (goto-char (point-min))
  (replace-regexp (concat prefix "xerprn") "nsp_calpack_xerprn" )
  (goto-char (point-min))
  (replace-regexp (concat prefix "xersve") "nsp_calpack_xersve" )
  (goto-char (point-min))
  (replace-regexp (concat prefix "xgetua") "nsp_calpack_xgetua" )
  (goto-char (point-min))
  (replace-regexp (concat prefix "zabs") "nsp_calpack_zabs" )
  (goto-char (point-min))
  (replace-regexp (concat prefix "zacai") "nsp_calpack_zacai" )
  (goto-char (point-min))
  (replace-regexp (concat prefix "zacon") "nsp_calpack_zacon" )
  (goto-char (point-min))
  (replace-regexp (concat prefix "zairy") "nsp_calpack_zairy" )
  (goto-char (point-min))
  (replace-regexp (concat prefix "zasyi") "nsp_calpack_zasyi" )
  (goto-char (point-min))
  (replace-regexp (concat prefix "zbesh") "nsp_calpack_zbesh" )
  (goto-char (point-min))
  (replace-regexp (concat prefix "zbeshg") "nsp_calpack_zbeshg" )
  (goto-char (point-min))
  (replace-regexp (concat prefix "zbeshv") "nsp_calpack_zbeshv" )
  (goto-char (point-min))
  (replace-regexp (concat prefix "zbesi") "nsp_calpack_zbesi" )
  (goto-char (point-min))
  (replace-regexp (concat prefix "zbesig") "nsp_calpack_zbesig" )
  (goto-char (point-min))
  (replace-regexp (concat prefix "zbesiv") "nsp_calpack_zbesiv" )
  (goto-char (point-min))
  (replace-regexp (concat prefix "zbesj") "nsp_calpack_zbesj" )
  (goto-char (point-min))
  (replace-regexp (concat prefix "zbesjg") "nsp_calpack_zbesjg" )
  (goto-char (point-min))
  (replace-regexp (concat prefix "zbesjv") "nsp_calpack_zbesjv" )
  (goto-char (point-min))
  (replace-regexp (concat prefix "zbesk") "nsp_calpack_zbesk" )
  (goto-char (point-min))
  (replace-regexp (concat prefix "zbeskg") "nsp_calpack_zbeskg" )
  (goto-char (point-min))
  (replace-regexp (concat prefix "zbeskv") "nsp_calpack_zbeskv" )
  (goto-char (point-min))
  (replace-regexp (concat prefix "zbesy") "nsp_calpack_zbesy" )
  (goto-char (point-min))
  (replace-regexp (concat prefix "zbesyg") "nsp_calpack_zbesyg" )
  (goto-char (point-min))
  (replace-regexp (concat prefix "zbesyv") "nsp_calpack_zbesyv" )
  (goto-char (point-min))
  (replace-regexp (concat prefix "zbinu") "nsp_calpack_zbinu" )
  (goto-char (point-min))
  (replace-regexp (concat prefix "zbknu") "nsp_calpack_zbknu" )
  (goto-char (point-min))
  (replace-regexp (concat prefix "zbuni") "nsp_calpack_zbuni" )
  (goto-char (point-min))
  (replace-regexp (concat prefix "zbunk") "nsp_calpack_zbunk" )
  (goto-char (point-min))
  (replace-regexp (concat prefix "zdiv") "nsp_calpack_zdiv" )
  (goto-char (point-min))
  (replace-regexp (concat prefix "zexp") "nsp_calpack_zexp" )
  (goto-char (point-min))
  (replace-regexp (concat prefix "zkscl") "nsp_calpack_zkscl" )
  (goto-char (point-min))
  (replace-regexp (concat prefix "zlog") "nsp_calpack_zlog" )
  (goto-char (point-min))
  (replace-regexp (concat prefix "zmlri") "nsp_calpack_zmlri" )
  (goto-char (point-min))
  (replace-regexp (concat prefix "zmlt") "nsp_calpack_zmlt" )
  (goto-char (point-min))
  (replace-regexp (concat prefix "zrati") "nsp_calpack_zrati" )
  (goto-char (point-min))
  (replace-regexp (concat prefix "zs1s2") "nsp_calpack_zs1s2" )
  (goto-char (point-min))
  (replace-regexp (concat prefix "zseri") "nsp_calpack_zseri" )
  (goto-char (point-min))
  (replace-regexp (concat prefix "zshch") "nsp_calpack_zshch" )
  (goto-char (point-min))
  (replace-regexp (concat prefix "zsqrt") "nsp_calpack_zsqrt" )
  (goto-char (point-min))
  (replace-regexp (concat prefix "zuchk") "nsp_calpack_zuchk" )
  (goto-char (point-min))
  (replace-regexp (concat prefix "zunhj") "nsp_calpack_zunhj" )
  (goto-char (point-min))
  (replace-regexp (concat prefix "zuni1") "nsp_calpack_zuni1" )
  (goto-char (point-min))
  (replace-regexp (concat prefix "zuni2") "nsp_calpack_zuni2" )
  (goto-char (point-min))
  (replace-regexp (concat prefix "zunik") "nsp_calpack_zunik" )
  (goto-char (point-min))
  (replace-regexp (concat prefix "zunk1") "nsp_calpack_zunk1" )
  (goto-char (point-min))
  (replace-regexp (concat prefix "zunk2") "nsp_calpack_zunk2" )
  (goto-char (point-min))
  (replace-regexp (concat prefix "zuoik") "nsp_calpack_zuoik" )
  (goto-char (point-min))
  (replace-regexp (concat prefix "zwrsk") "nsp_calpack_zwrsk" )
  )

(defun job () 
  (test)
  (save-buffer)
  )


