SHELL=/bin/sh

include ../Path.incl

# this include is needed to compile sci files 
# include $(SCIDIR)/macros/Makefile.lib

SUBDIRS = blocks scicos importapi

# this include is needed to propagate make to subdirs

include ./Makefile.incl

