SHELL = /bin/sh

include ../../Path.incl

SUBDIRS = \
	Branching Events IntegerOp Iterators Linear \
	MatrixOp Misc ModElectrical Modelica ModHydraulics \
	ModLinear NonLinear PDE Sinks Sources \
	Threshold ModEni

include ../Makefile.incl

