function options=default_options()
// using a hash table 
  col3d=[0.8 0.8 0.8]
  options=hash_create(6, Background=[8 1],...
		      Link=[1,5],...
		      ID=list([5 0],[4 0]),...
		      Cmap=col3d,...
		      D3=list(%t,33) ); 
  options('3D')=list(%t,33);
endfunction

