SHELL = /bin/sh

# We assume that Path.incl contains a relative path to nsp
TOP=../..
include $(TOP)/Path.incl
SCIDIR :=$(TOP)/$(SCIDIR)

# this include is needed to compile sci files 
include $(SCIDIR)/macros/Makefile.lib

# this include is needed to compile sub directories
SUBDIRS=menus codegeneration icon_edit

include ../Makefile.incl

